improve build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,12 +1,39 @@
 #!/bin/bash
 set -e
 
-mkdir -p patches
+usage() {
+cat << EOF
+Usage: $0 [OPTIONS]
+Build a new Python R image.
+Options:
+    -c, --use-cache Use layer cache when building a new image.
+EOF
+}
 
-# Default behavior is to do everything from scratch.
-# The --use-cache option is useful if you're iterating on a broken build.
-if [[ "$1" ==  "--use-cache" ]]; then
-    docker build --rm -t kaggle/rstats-build .
-else
-    docker build --pull --rm --no-cache -t kaggle/rstats-build .
-fi
+CACHE_FLAG='--no-cache'
+
+while :; do
+    case "$1" in 
+        -h|--help)
+            usage
+            exit
+            ;;
+        -c|--use-cache)
+            CACHE_FLAG=''
+            ;;
+        -?*)
+            usage
+            printf 'ERROR: Unknown option: %s\n' "$1" >&2
+            exit
+            ;;
+        *)            
+            break
+    esac
+
+    shift
+done
+
+readonly CACHE_FLAG
+
+set -x
+docker build --rm --pull $CACHE_FLAG -t kaggle/rstats-build .
