Add --base-image-tag to build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -8,6 +8,7 @@ Build a new Docker R image.
 Options:
     -c, --use-cache Use layer cache when building a new image.
     -g, --gpu       Build an image with GPU support.
+    -b, --base-image-tag TAG  Base image tag. Defaults to value defined in DOCKERFILE.
 EOF
 }
 
@@ -15,6 +16,7 @@ CACHE_FLAG='--no-cache'
 DOCKERFILE='Dockerfile'
 IMAGE_TAG='kaggle/rstats-build'
 NCPUS=$(nproc || echo 1)
+BUILD_ARGS=''
 
 while :; do
     case "$1" in 
@@ -29,6 +31,15 @@ while :; do
             IMAGE_TAG='kaggle/rstats-gpu-build'
             DOCKERFILE='gpu.Dockerfile'
             ;;
+        -b|--base-image-tag)
+            if [[ -z $2 ]]; then
+                usage
+                printf 'ERROR: No TAG specified after the %s flag.\n' "$1" >&2
+                exit
+            fi
+            BUILD_ARGS="--build-arg BASE_TAG=$2"
+            shift # skip the flag value
+            ;;
         -?*)
             usage
             printf 'ERROR: Unknown option: %s\n' "$1" >&2
@@ -41,9 +52,12 @@ while :; do
     shift
 done
 
+BUILD_ARGS+=" --build-arg ncpus=$NCPUS"
+
 readonly CACHE_FLAG
 readonly DOCKERFILE
 readonly IMAGE_TAG
+readonly BUILD_ARGS
 
 set -x
-docker build --rm --pull $CACHE_FLAG -t "$IMAGE_TAG" -f "$DOCKERFILE" --build-arg ncpus=$NCPUS .
+docker build --rm --pull $CACHE_FLAG -t "$IMAGE_TAG" -f "$DOCKERFILE" $BUILD_ARGS .
